const data = [
  {
    img: "",
    title: "Beautiful You",
    price: "",
    discount: "",
    star: "",
    rating: "",
  },
  {
    img: "",
    title: "Beautiful You",
    price: "",
    discount: "",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_5mDZQZkpU3GvpHgiFNc0hS9Ur.jpg",
    title: "Timeless Elegance",
    price: "249,000 ₫",
    discount: "349,000 ₫",
    star: "5.0",
    rating: "(32)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_gO35Rzwuwfl2OwZpBbefqwUeo.jpg",
    title: "Under The Blue Sky",
    price: "379,000 ₫",
    discount: "449,000 ₫",
    star: "4.9",
    rating: "(42)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_Ij9lTCIwGFnvpg69r9onYPcYc.jpg",
    title: "Mon Bel Amour",
    price: "449,000 ₫",
    discount: "499,000 ₫",
    star: "4.9",
    rating: "(39)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_nV1G9ej3pJ3QuWRts1rZuqrYy.jpg",
    title: "Felicity",
    price: "449,000 ₫",
    discount: "",
    star: "5.0",
    rating: "(40)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_c2pSbQz2Z3ax0rw5iLiJOtG8b.jpg",
    title: "Summer Delight",
    price: "479,000 ₫",
    discount: "499,000 ₫",
    star: "5.0",
    rating: "(33)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_Sp4Ke6mMZ6LuF0bMFSTHtZcMi.jpg",
    title: "Forever 18 (18 bông hồng)",
    price: "479,000 ₫",
    discount: "499,000 ₫",
    star: "5.0",
    rating: "(37)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_OUvy2lj6TmRqfMw3B8Pl3PX0u.jpg",
    title: "Sunny Smile",
    price: "249,000 ₫",
    discount: "349,000 ₫",
    star: "4.9",
    rating: "(34)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_ogwc2LSMsBDMWDpmConZc4JXo.jpg",
    title: "Heart To Heart",
    price: "529,000 ₫",
    discount: "699,000 ₫",
    star: "5.0",
    rating: "(5)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_OXoen2MmQ0b6Pylmj3A2FigmS.jpg",
    title: "La Vie En Rose",
    price: "579,000 ₫",
    discount: "",
    star: "5.0",
    rating: "(34)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_eCXNkR5pWnIO7s3kRUEamWK78.jpg",
    title: "Carla",
    price: "529,000 ₫",
    discount: "649,000 ₫",
    star: "5.0",
    rating: "(41)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_Z4oZrBsaTyzpSJa6qUR3tFz0l.jpg",
    title: "Fly Me To The Moon",
    price: "579,000 ₫",
    discount: "749,000 ₫",
    star: "4.8",
    rating: "(12)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_mjmqovrITO5arveNiXOvTO9W8.jpg",
    title: "Fall For You",
    price: "599,000 ₫",
    discount: "",
    star: "5.0",
    rating: "(35)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_zjidh0APMf7FwIAT4BmikHpCZ.jpg",
    title: "Syrah",
    price: "599,000 ₫",
    discount: "",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_IQLkJNQ0oXjHkab7aDoJwIIqP.jpg",
    title: "Dreamcatcher",
    price: "479,000 ₫",
    discount: "649,000 ₫",
    star: "5.0",
    rating: "(7)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_Gh75OoiQxBxTHl7M688XvgE3j.jpg",
    title: "Chocolate As Sweet As You",
    price: "549,000 ₫",
    discount: "699,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_mf77CBUH3LBkQxqLMiUI1AN0D.jpg",
    title: "Loving You Đặc Biệt",
    price: "779,000 ₫",
    discount: "979,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_DBUyG1aaVJJUuoVMeiIEvEh05.jpg",
    title: "La Vie En Rose Đặc Biệt",
    price: "1,099,000 ₫",
    discount: "1,299,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_OWLu4Dn0HU1Z8pcUUh6uaejTv.jpg",
    title: "Combo Confident",
    price: "419,000 ₫",
    discount: "649,000 ₫",
    star: "5.0",
    rating: "(4)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_b4hmdZstSPlOyCIkjGtGIVQEt.jpg",
    title: "Happy Success",
    price: "299,000 ₫",
    discount: "449,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_RUx0WSTf5PuZHzuhVaZ94fby3.jpg",
    title: "Sunset Love",
    price: "349,000 ₫",
    discount: "449,000 ₫",
    star: "5.0",
    rating: "(35)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_8jeJteVWHwjVkfuxFYgt6Z7VS.jpg",
    title: "Green Garden",
    price: "379,000 ₫",
    discount: "599,000 ₫",
    star: "5.0",
    rating: "(5)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_cmsFuhS7uhWt9jvBO1v7h3UlK.jpg",
    title: "Sweet Teddy",
    price: "499,000 ₫",
    discount: "699,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_tkVNLrfydlDGvAaAfGhGsbv22.jpg",
    title: "Stay Spright",
    price: "879,000 ₫",
    discount: "949,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_8z6zRxDdTilwneBRrnJUkuGH9.jpg",
    title: "Day Dreamer",
    price: "529,000 ₫",
    discount: "699,000 ₫",
    star: "5.0",
    rating: "(1)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_oh6NQYkalgSuDl8oXOaAE95UD.jpg",
    title: "Papillion",
    price: "449,000 ₫",
    discount: "499,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_0Ot9C7zlis28CUjvdCM5ea3UX.jpg",
    title: "Our Lyrical",
    price: "479,000 ₫",
    discount: "499,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_XkiCe1oCeZHQ3mqV2MILF85l7.jpg",
    title: "Lovely Bunny",
    price: "499,000 ₫",
    discount: "599,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_Kejtu46HSJBK7dqPZ0vOoOfsN.jpg",
    title: "Chloris",
    price: "429,000 ₫",
    discount: "599,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_LawecDh8MFyDh6UybNE9h2UMJ.jpg",
    title: "Be With You",
    price: "499,000 ₫",
    discount: "",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_gzMOfzjK6byk15tZZLzAvbTo6.jpg",
    title: "Bittersweet",
    price: "749,000 ₫",
    discount: "779,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_oh6NQYkalgSuDl8oXOaAE95UD.jpg",
    title: "Papillion",
    price: "449,000 ₫",
    discount: "499,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_d5WZsXSHqi3EJrm93aNfIcmc0.jpg",
    title: "Darling Darling",
    price: "579,000 ₫",
    discount: "699,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_hiQZJSJltZGQB6lL68ZReftoZ.jpg",
    title: "Jane's Garden",
    price: "479,000 ₫",
    discount: "599,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_ExPyDub9F1DRF2OEVQB4aEFVr.jpg",
    title: "Spring Morning (Giỏ Đen)",
    price: "729,000 ₫",
    discount: "899,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_JuPGZGW1NswYM7aEcjDfZUpVO.jpg",
    title: "Two Kisses",
    price: "1,299,000 ₫",
    discount: "",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_9qco7fks0tuAx1GnFFuEmq9cx.jpg",
    title: "Virgorousness",
    price: "2,149,000 ₫",
    discount: "2,399,000 ₫",
    star: "5.0",
    rating: "(5)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_miS7oRT6HVVNseUHTM3uTEdo2.jpg",
    title: "Come And Kiss Me",
    price: "599,000 ₫",
    discount: "699,000 ₫",
    star: "4.5",
    rating: "(2)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_g75C9LDS0Qks2FcDBROwKz9oS.jpg",
    title: "Coral Pink",
    price: "729,000 ₫",
    discount: "799,000 ₫",
    star: "4.8",
    rating: "(4)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_1WV0QIkpD4E5V38hBUrBDaIJ9.jpg",
    title: "Poetic Lover",
    price: "849,000 ₫",
    discount: "949,000 ₫",
    star: "5.0",
    rating: "(2)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_cWnDJNUlmT6hFYWXkmyy1FVO2.jpg",
    title: "City Of Stars",
    price: "749,000 ₫",
    discount: "799,000 ₫",
    star: "5.0",
    rating: "(4)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_ntNWGDTDgaKd0izbihSkLzqSg.jpg",
    title: "Secret Lover",
    price: "879,000 ₫",
    discount: "999,000 ₫",
    star: "5.0",
    rating: "(2)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_L6JyEkN7L1KuXYmlkd0EE3VNo.jpg",
    title: "Pretty Glory",
    price: "1,399,000 ₫",
    discount: "1,999,000 ₫",
    star: "4.9",
    rating: "(10)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_wK5OAWvVk0DxvTiuAwwm5TDHT.jpg",
    title: "Cool Breeze",
    price: "479,000 ₫",
    discount: "549,000 ₫",
    star: "4.9",
    rating: "(9)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_b8R4yHgGYbmQSj4m9TxMwU5pu.jpg",
    title: "Fabulously Red",
    price: "529,000 ₫",
    discount: "599,000 ₫",
    star: "4.9",
    rating: "(8)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_YGpnmvWgkkWyayZMbgtnneKNd.jpg",
    title: "Kindness",
    price: "599,000 ₫",
    discount: "999,000 ₫",
    star: "4.8",
    rating: "(5)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_q4oTIzgrhbYin8GEZhUWirwDF.jpg",
    title: "Young &amp; Beautiful",
    price: "549,000 ₫",
    discount: "749,000 ₫",
    star: "4.8",
    rating: "(6)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_UvpBsN72lQnNW2YwHBR3l1RtT.jpg",
    title: "Ms. Spring",
    price: "699,000 ₫",
    discount: "799,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_mf77CBUH3LBkQxqLMiUI1AN0D.jpg",
    title: "Loving You Đặc Biệt",
    price: "779,000 ₫",
    discount: "979,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_2QCFXJwaWfdFnnCAFMXzOUzSF.jpg",
    title: "A Million Dreams",
    price: "1,099,000 ₫",
    discount: "1,249,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_RHoqeVFT80TrhhXadDcjnISLA.jpg",
    title: "Charming Rune",
    price: "1,249,000 ₫",
    discount: "1,349,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_VdUW9QjLpAvzhljjwyBmWDnbp.jpg",
    title: "Combo Brilliant",
    price: "429,000 ₫",
    discount: "599,000 ₫",
    star: "5.0",
    rating: "(1)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_GT943NKaTnCTjua0PmmLCJby4.jpg",
    title: "Combo Blue Dream",
    price: "1,199,000 ₫",
    discount: "1,239,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_BxTI0jKUtKnB5reQ4Se18jJVE.jpg",
    title: "Bánh Kem Passion Fruit",
    price: "599,000 ₫",
    discount: "799,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_DCNtUnv48ikjK76GVCcI2b1m9.jpg",
    title: "Bánh Kem Macaron Delight",
    price: "599,000 ₫",
    discount: "",
    star: "5.0",
    rating: "(12)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_IcrYCqG6IfnQNSTnzrj0XufEk.jpg",
    title: "Nến Thơm Falling in Love (80g)",
    price: "279,000 ₫",
    discount: "329,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_S5xbzZWAYFmjUUWgRMMl00IMu.jpg",
    title: "Nến Thơm For My Beloved",
    price: "499,000 ₫",
    discount: "549,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_MdwrZVg4NKxQtN5e5a7fs1BuL.jpg",
    title: "Tinh Dầu Ướp Hương",
    price: "249,000 ₫",
    discount: "299,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_kkYTUSbihxtRsUMldxHdM6olH.png",
    title: "Nến Thơm Sea Salt",
    price: "349,000 ₫",
    discount: "529,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_AQ9M8dgD1RpZR7GlaGpvWLQ5H.png",
    title: "Nến Thơm Choco Mint",
    price: "349,000 ₫",
    discount: "429,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_pDCHHWQTEFvbhYGmj5FMDbCzm.png",
    title: "Nến Thơm Juicy Pear",
    price: "429,000 ₫",
    discount: "499,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_SJMnOGtU81Nbx3gcLByGexoQR.jpg",
    title: "Nến Thơm A Piece of Love",
    price: "829,000 ₫",
    discount: "899,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_LJ7YgoabLZFXFSoT2Iy4Uw8j0.jpg",
    title: "Nến Thơm Falling in Love (175g)",
    price: "449,000 ₫",
    discount: "499,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_1LGxoNXAqLh6epNsrEPsqPD0T.jpg",
    title: "Tropical Love",
    price: "449,000 ₫",
    discount: "499,000 ₫",
    star: "5.0",
    rating: "(8)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_fK3SHHjjbVXhHgCDmlBqtZ2w1.jpg",
    title: "Bộ Quà Tặng Thiên Nhiên",
    price: "449,000 ₫",
    discount: "459,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_ZIpPm5RsnIr4lnsjkO9KjJIZs.jpg",
    title: "Tinh Dầu Khuếch Tán",
    price: "449,000 ₫",
    discount: "479,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_s3qnk5Snes2kZ23pzLLTVD8SR.jpg",
    title: "Bánh Kem Cam",
    price: "449,000 ₫",
    discount: "579,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_Md8oyvaIktNh3KYdF2SOMPMee.jpg",
    title: "Sunny Achievement",
    price: "1,699,000 ₫",
    discount: "1,999,000 ₫",
    star: "5.0",
    rating: "(1)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_GlMOrQy4K6IMEJlwJl6fd4QlN.jpg",
    title: "Time To Cheer",
    price: "1,949,000 ₫",
    discount: "2,499,000 ₫",
    star: "5.0",
    rating: "(5)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_AYNwTTirgfAdL9am2wAzOy8XH.jpg",
    title: "The Pinnacle Of Success",
    price: "1,899,000 ₫",
    discount: "2,399,000 ₫",
    star: "5.0",
    rating: "(1)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_iSptXdJUfFX9l0SzsD5cUdN1N.jpg",
    title: "Glamorous",
    price: "1,599,000 ₫",
    discount: "1,799,000 ₫",
    star: "5.0",
    rating: "(1)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_fUkzClmTYDaps9PEaEkMI89Tc.jpg",
    title: "Marvellous",
    price: "999,000 ₫",
    discount: "1,299,000 ₫",
    star: "4.0",
    rating: "(1)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_HATKAHLl99po5EmSCkJCnkL1q.jpg",
    title: "Urban Success",
    price: "1,999,000 ₫",
    discount: "2,099,000 ₫",
    star: "5.0",
    rating: "(2)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_pLaMXBhaTFv8kOEHowFIY8RSo.jpg",
    title: "Stuck In Love",
    price: "379,000 ₫",
    discount: "399,000 ₫",
    star: "5.0",
    rating: "(5)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_5WxbtQDZtB10W4qLyp53t5E4X.jpg",
    title: "Dream Of You",
    price: "429,000 ₫",
    discount: "599,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_NdME0y5bcvPstZb6gjuOXT80Y.jpg",
    title: "Melted Love",
    price: "329,000 ₫",
    discount: "399,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_4w0xfoHcegYsaprV3j4v613J8.jpg",
    title: "Pink Moon",
    price: "449,000 ₫",
    discount: "599,000 ₫",
    star: "5.0",
    rating: "(10)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_tNjLOmf4wCOI0JIyQk9xXZrzS.jpg",
    title: "Mindful Soul",
    price: "429,000 ₫",
    discount: "499,000 ₫",
    star: "5.0",
    rating: "(36)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_3D2UL6SVyExR4umGI3HBrtCJW.jpg",
    title: "Doors To Heaven",
    price: "399,000 ₫",
    discount: "599,000 ₫",
    star: "4.8",
    rating: "(5)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_ahA8qqVDC3zm4QSkfvJaMymAs.jpg",
    title: "Hoa Cưới Appliqué Bridal",
    price: "399,000 ₫",
    discount: "",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_JJgP3G1qohzPrYZQphd4gjcbr.jpg",
    title: "Hoa Cưới All My Life Bridal",
    price: "349,000 ₫",
    discount: "379,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_FuszHkgvRuhzp1ZOkVknn9XY0.jpg",
    title: "Hoa Cưới The Macarena Bridal",
    price: "449,000 ₫",
    discount: "",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_Ytgbc3n7S5bGFCs0O1MP24DXB.jpg",
    title: "Hoa Cưới Wear Me Corsage Bridal",
    price: "449,000 ₫",
    discount: "",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_G4TJE84gbzGk0fBoASfWhAlTa.jpg",
    title: "Hoa Cưới Love Avenue Bridal",
    price: "299,000 ₫",
    discount: "",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_LVPQqOrjHp03U5AY5N4TTjQqi.jpg",
    title: "Hoa Cưới Stay With Me Bridal",
    price: "349,000 ₫",
    discount: "599,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_kTYl2jGHR1yrkST3537x91TuF.jpg",
    title: "Chậu Hoa Lan Break Of Dawn",
    price: "699,000 ₫",
    discount: "799,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_59mvdhmfiu0DyboYfNQjQ62rT.jpg",
    title: "Chậu Hoa Lan Cheers To 2022",
    price: "749,000 ₫",
    discount: "799,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_pH4ek5A35YV11DGFGlKvE7Ala.jpg",
    title: "Chậu Hoa Lan Midnight",
    price: "1,599,000 ₫",
    discount: "1,799,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_UcstJKWM9rusB0PUO50hcizvg.jpg",
    title: "Chậu Hoa Lan Wishes Come True",
    price: "1,599,000 ₫",
    discount: "1,799,000 ₫",
    star: "5.0",
    rating: "(1)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_wOAx0obJa3LolhMKhTcrXF68v.jpg",
    title: "Chậu Hoa Lan Wonderful Journey",
    price: "1,599,000 ₫",
    discount: "1,799,000 ₫",
    star: "5.0",
    rating: "(1)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_iHkQ6cmhXUmWx5ElwCt24ENsm.jpg",
    title: "Chậu Hoa Lan Smooth Sailing",
    price: "2,099,000 ₫",
    discount: "2,299,000 ₫",
    star: "5.0",
    rating: "(1)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/250_kUPN4zrcZ1blZi7MMdyCFB3TB.jpg",
    title: 'Chậu Kim Tiền Thank You Dad',
    price: "379,000 ₫",
    discount: "399,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_2KH72aRsTOwKiedKZ9sr7UPdq.jpg",
    title: 'Chậu Kim Ngân My Daddy Is The Best',
    price: "399,000 ₫",
    discount: "499,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_es4660YZw9ELnjkGRuZdZtLM1.jpg",
    title: "Chậu Sen Đá Size Đại",
    price: "199,000 ₫",
    discount: "359,000 ₫",
    star: "5.0",
    rating: "(1)",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_Xgezj0QLN1aHRxXN3ZRLJBcLj.jpg",
    title: "Chậu Lưỡi Hổ I Love Dad",
    price: "299,000 ₫",
    discount: "",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_iegRzbHsiFBkoXijuQ47KD8gb.jpg",
    title: 'Chậu Lưỡi Hổ Happy Fathers Day',
    price: "349,000 ₫",
    discount: "399,000 ₫",
    star: "",
    rating: "",
  },
  {
    img: "https://assets.flowerstore.ph/public/tenantVN/app/assets/images/product/350_ZBxehjm28OYxyi361rnHaREnN.jpg",
    title: "Sen Đá Hà Mã Xanh",
    price: "229,000 ₫",
    discount: "249,000 ₫",
    star: "5.0",
    rating: "(1)",
  },
];

module.exports = data;
